name: Build JS
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43
          actions-cache-folder: "emsdk-cache"
      - name: Configure venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install premake
        run: |
          wget -q https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xf premake-5.0.0-beta2-linux.tar.gz
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin
          pip3 install ply
      - name: Install modules
        run: cd js && npm install
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build
        working-directory: wasm
        run: |
          OUT_DIR=build/webgl2_advanced_single/bin/release ./build_wasm.sh -r webgl2 -s release

      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts
          echo "// Build: ${GITHUB_SHA}" | cat - wasm/build/webgl2_advanced_single/bin/release/webgl2_advanced_single.mjs > artifacts/webgl2_advanced_single.mjs
          echo "// Build: ${GITHUB_SHA}" | cat - js/src/rive_advanced.mjs.d.ts > artifacts/rive_advanced.mjs.d.ts

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rive-${{ github.sha }}
          path: artifacts/
