name: Build JS
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43
          actions-cache-folder: "emsdk-cache"
      - name: Configure venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install premake
        run: |
          wget -q https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xf premake-5.0.0-beta2-linux.tar.gz
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin
          pip3 install ply
      - name: Install modules
        run: cd js && npm install
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build
        working-directory: wasm
        run: |
          OUT_DIR=build/webgl2_advanced_single/bin/release ./build_wasm.sh -r webgl2 -s release

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          # Attempt to get the latest tag reachable from the current commit
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Add Build Comment to webgl2_advanced_single.mjs
        working-directory: wasm/build/webgl2_advanced_single/bin/release
        run: |
          if [ "$LATEST_TAG" != "no-tag" ]; then
            echo "// Build: ${LATEST_TAG} ${GITHUB_SHA}" | cat - webgl2_advanced_single.mjs > temp && mv temp webgl2_advanced_single.mjs
          else
            echo "// Build: ${GITHUB_SHA}" | cat - webgl2_advanced_single.mjs > temp && mv temp webgl2_advanced_single.mjs
          fi

      - name: Add Build Comment to rive_advanced.mjs.d.ts
        working-directory: js/src
        run: |
          if [ "$LATEST_TAG" != "no-tag" ]; then
            echo "// Build: ${LATEST_TAG} ${GITHUB_SHA}" | cat - rive_advanced.mjs.d.ts > temp && mv temp rive_advanced.mjs.d.ts
          else
            echo "// Build: ${GITHUB_SHA}" | cat - rive_advanced.mjs.d.ts > temp && mv temp rive_advanced.mjs.d.ts
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            wasm/build/webgl2_advanced_single/bin/release/webgl2_advanced_single.mjs
            js/src/rive_advanced.mjs.d.ts
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: build-${{ github.run_number }}
          name: Release build-${{ github.run_number }}
          draft: false
          prerelease: false
