name: Build WASM
on:
  push:
    branches:
      - dopple/master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install ply from pip
        run: pip install ply
      - name: Build
        env:
          OUT_DIR: build
        run: cd wasm && ./build_wasm.sh -r webgl2 release
